name: Rename
version: @version@-@apiversion@
author: DartPower
website: https://github.com/dptmc/DPT-PluginRepoTemplate
main: io.dpteam.Rename.Main
api-version: 1.13
commands:
  rename:
    permission: rename.allow
    permission-message: You are missing a permission. rename.allow
  relore:
    permission: rename.allow
    permission-message: You are missing a permission. rename.allow
